/*
 * Created on 2020-05-29 ( Time 16:10:09 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package org.demo.web.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import org.demo.web.common.AbstractController;
import org.demo.web.common.FormMode;
import org.demo.web.common.Message;
import org.demo.web.common.MessageType;

//--- Entities
import org.demo.bean.Countrylanguage;
import org.demo.bean.Country;

//--- Services 
import org.demo.business.service.CountrylanguageService;
import org.demo.business.service.CountryService;

//--- List Items 
import org.demo.web.listitem.CountryListItem;

/**
 * Spring MVC controller for 'Countrylanguage' management.
 */
@Controller
@RequestMapping("/countrylanguage")
public class CountrylanguageController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "countrylanguage";
	private static final String MAIN_LIST_NAME   = "list";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "countrylanguage/form";
	private static final String JSP_LIST   = "countrylanguage/list";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/countrylanguage/create";
	private static final String SAVE_ACTION_UPDATE   = "/countrylanguage/update";

	//--- Main entity service
	@Resource
    private CountrylanguageService countrylanguageService; // Injected by Spring
	//--- Other service(s)
	@Resource
    private CountryService countryService; // Injected by Spring

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public CountrylanguageController() {
		super(CountrylanguageController.class, MAIN_ENTITY_NAME );
		log("CountrylanguageController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------
	/**
	 * Populates the combo-box "items" for the referenced entity "Country"
	 * @param model
	 */
	private void populateListOfCountryItems(Model model) {
		List<Country> list = countryService.findAll();
		List<CountryListItem> items = new LinkedList<CountryListItem>();
		for ( Country country : list ) {
			items.add(new CountryListItem( country ) );
		}
		model.addAttribute("listOfCountryItems", items ) ;
	}


	/**
	 * Populates the Spring MVC model with the given entity and eventually other useful data
	 * @param model
	 * @param countrylanguage
	 */
	private void populateModel(Model model, Countrylanguage countrylanguage, FormMode formMode) {
		//--- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, countrylanguage);
		if ( formMode == FormMode.CREATE ) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE); 			
			//--- Other data useful in this screen in "create" mode (all fields)
			populateListOfCountryItems(model);
		}
		else if ( formMode == FormMode.UPDATE ) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE); 			
			//--- Other data useful in this screen in "update" mode (only non-pk fields)
		}
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of Countrylanguage found in the database
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping()
	public String list(Model model) {
		log("Action 'list'");
		List<Countrylanguage> list = countrylanguageService.findAll();
		model.addAttribute(MAIN_LIST_NAME, list);		
		return JSP_LIST;
	}

	/**
	 * Shows a form page in order to create a new Countrylanguage
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(Model model) {
		log("Action 'formForCreate'");
		//--- Populates the model with a new instance
		Countrylanguage countrylanguage = new Countrylanguage();	
		populateModel( model, countrylanguage, FormMode.CREATE);
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing Countrylanguage
	 * @param model Spring MVC model
	 * @param countrycode  primary key element
	 * @param language  primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{countrycode}/{language}")
	public String formForUpdate(Model model, @PathVariable("countrycode") String countrycode, @PathVariable("language") String language ) {
		log("Action 'formForUpdate'");
		//--- Search the entity by its primary key and stores it in the model 
		Countrylanguage countrylanguage = countrylanguageService.findById(countrycode, language);
		populateModel( model, countrylanguage, FormMode.UPDATE);		
		return JSP_FORM;
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param countrylanguage  entity to be created
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(@Valid Countrylanguage countrylanguage, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'create'");
		try {
			if (!bindingResult.hasErrors()) {
				Countrylanguage countrylanguageCreated = countrylanguageService.create(countrylanguage); 
				model.addAttribute(MAIN_ENTITY_NAME, countrylanguageCreated);

				//---
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				return redirectToForm(httpServletRequest, countrylanguage.getCountrycode(), countrylanguage.getLanguage() );
			} else {
				populateModel( model, countrylanguage, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'create' : Exception - " + e.getMessage() );
			messageHelper.addException(model, "countrylanguage.error.create", e);
			populateModel( model, countrylanguage, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param countrylanguage  entity to be updated
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update" ) // GET or POST
	public String update(@Valid Countrylanguage countrylanguage, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {
				//--- Perform database operations
				Countrylanguage countrylanguageSaved = countrylanguageService.update(countrylanguage);
				model.addAttribute(MAIN_ENTITY_NAME, countrylanguageSaved);
				//--- Set the result message
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				log("Action 'update' : update done - redirect");
				return redirectToForm(httpServletRequest, countrylanguage.getCountrycode(), countrylanguage.getLanguage());
			} else {
				log("Action 'update' : binding errors");
				populateModel( model, countrylanguage, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			messageHelper.addException(model, "countrylanguage.error.update", e);
			log("Action 'update' : Exception - " + e.getMessage() );
			populateModel( model, countrylanguage, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param redirectAttributes
	 * @param countrycode  primary key element
	 * @param language  primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{countrycode}/{language}") // GET or POST
	public String delete(RedirectAttributes redirectAttributes, @PathVariable("countrycode") String countrycode, @PathVariable("language") String language) {
		log("Action 'delete'" );
		try {
			countrylanguageService.delete( countrycode, language );
			//--- Set the result message
			messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"delete.ok"));	
		} catch(Exception e) {
			messageHelper.addException(redirectAttributes, "countrylanguage.error.delete", e);
		}
		return redirectToList();
	}

}
