/*
 * Created on 2020-05-29 ( Time 14:26:45 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package org.demo.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.demo.bean.City;
import org.demo.bean.jpa.CityEntity;
import org.demo.bean.jpa.CountryEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class CityServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public CityServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'CityEntity' to 'City'
	 * @param cityEntity
	 */
	public City mapCityEntityToCity(CityEntity cityEntity) {
		if(cityEntity == null) {
			return null;
		}

		//--- Generic mapping 
		City city = map(cityEntity, City.class);

		//--- Link mapping ( link to Country )
		if(cityEntity.getCountry() != null) {
			city.setCountrycode(cityEntity.getCountry().getCode());
		}
		return city;
	}
	
	/**
	 * Mapping from 'City' to 'CityEntity'
	 * @param city
	 * @param cityEntity
	 */
	public void mapCityToCityEntity(City city, CityEntity cityEntity) {
		if(city == null) {
			return;
		}

		//--- Generic mapping 
		map(city, cityEntity);

		//--- Link mapping ( link : city )
		if( hasLinkToCountry(city) ) {
			CountryEntity country1 = new CountryEntity();
			country1.setCode( city.getCountrycode() );
			cityEntity.setCountry( country1 );
		} else {
			cityEntity.setCountry( null );
		}

	}
	
	/**
	 * Verify that Country id is valid.
	 * @param Country Country
	 * @return boolean
	 */
	private boolean hasLinkToCountry(City city) {
		if(city.getCountrycode() != null) {
			return true;
		}
		return false;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}