/*
 * Created on 2020-05-29 ( Time 14:26:45 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package org.demo.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.demo.bean.Countrylanguage;
import org.demo.bean.jpa.CountrylanguageEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class CountrylanguageServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public CountrylanguageServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'CountrylanguageEntity' to 'Countrylanguage'
	 * @param countrylanguageEntity
	 */
	public Countrylanguage mapCountrylanguageEntityToCountrylanguage(CountrylanguageEntity countrylanguageEntity) {
		if(countrylanguageEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Countrylanguage countrylanguage = map(countrylanguageEntity, Countrylanguage.class);

		return countrylanguage;
	}
	
	/**
	 * Mapping from 'Countrylanguage' to 'CountrylanguageEntity'
	 * @param countrylanguage
	 * @param countrylanguageEntity
	 */
	public void mapCountrylanguageToCountrylanguageEntity(Countrylanguage countrylanguage, CountrylanguageEntity countrylanguageEntity) {
		if(countrylanguage == null) {
			return;
		}

		//--- Generic mapping 
		map(countrylanguage, countrylanguageEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}