/*
 * Created on 2020-05-29 ( Time 14:26:45 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package org.demo.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.demo.bean.Countrylanguage;
import org.demo.bean.jpa.CountrylanguageEntity;
import org.demo.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class CountrylanguageServiceMapperTest {

	private CountrylanguageServiceMapper countrylanguageServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		countrylanguageServiceMapper = new CountrylanguageServiceMapper();
		countrylanguageServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'CountrylanguageEntity' to 'Countrylanguage'
	 * @param countrylanguageEntity
	 */
	@Test
	public void testMapCountrylanguageEntityToCountrylanguage() {
		// Given
		CountrylanguageEntity countrylanguageEntity = new CountrylanguageEntity();
		countrylanguageEntity.setIsofficial(mockValues.nextString(1));
		countrylanguageEntity.setPercentage(mockValues.nextFloat());
		
		// When
		Countrylanguage countrylanguage = countrylanguageServiceMapper.mapCountrylanguageEntityToCountrylanguage(countrylanguageEntity);
		
		// Then
		assertEquals(countrylanguageEntity.getIsofficial(), countrylanguage.getIsofficial());
		assertEquals(countrylanguageEntity.getPercentage(), countrylanguage.getPercentage());
	}
	
	/**
	 * Test : Mapping from 'Countrylanguage' to 'CountrylanguageEntity'
	 */
	@Test
	public void testMapCountrylanguageToCountrylanguageEntity() {
		// Given
		Countrylanguage countrylanguage = new Countrylanguage();
		countrylanguage.setIsofficial(mockValues.nextString(1));
		countrylanguage.setPercentage(mockValues.nextFloat());

		CountrylanguageEntity countrylanguageEntity = new CountrylanguageEntity();
		
		// When
		countrylanguageServiceMapper.mapCountrylanguageToCountrylanguageEntity(countrylanguage, countrylanguageEntity);
		
		// Then
		assertEquals(countrylanguage.getIsofficial(), countrylanguageEntity.getIsofficial());
		assertEquals(countrylanguage.getPercentage(), countrylanguageEntity.getPercentage());
	}

}