/*
 * Created on 2020-05-29 ( Time 16:09:30 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package org.demo.bean;

import java.io.Serializable;

import javax.validation.constraints.*;


public class City implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    @Size( min = 1, max = 35 )
    private String name;

    @NotNull
    @Size( min = 1, max = 3 )
    private String countrycode;

    @NotNull
    @Size( min = 1, max = 20 )
    private String district;

    @NotNull
    private Integer population;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setName( String name ) {
        this.name = name;
    }
    public String getName() {
        return this.name;
    }

    public void setCountrycode( String countrycode ) {
        this.countrycode = countrycode;
    }
    public String getCountrycode() {
        return this.countrycode;
    }

    public void setDistrict( String district ) {
        this.district = district;
    }
    public String getDistrict() {
        return this.district;
    }

    public void setPopulation( Integer population ) {
        this.population = population;
    }
    public Integer getPopulation() {
        return this.population;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(countrycode);
        sb.append("|");
        sb.append(district);
        sb.append("|");
        sb.append(population);
        return sb.toString(); 
    } 


}
