/*
 * Created on 2020-05-29 ( Time 16:10:09 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package org.demo.bean;

import java.io.Serializable;

import javax.validation.constraints.*;


public class Countrylanguage implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    @Size( min = 1, max = 3 )
    private String countrycode;
    @NotNull
    @Size( min = 1, max = 30 )
    private String language;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    @Size( min = 1, max = 1 )
    private String isofficial;

    @NotNull
    private Float percentage;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setCountrycode( String countrycode ) {
        this.countrycode = countrycode ;
    }

    public String getCountrycode() {
        return this.countrycode;
    }

    public void setLanguage( String language ) {
        this.language = language ;
    }

    public String getLanguage() {
        return this.language;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setIsofficial( String isofficial ) {
        this.isofficial = isofficial;
    }
    public String getIsofficial() {
        return this.isofficial;
    }

    public void setPercentage( Float percentage ) {
        this.percentage = percentage;
    }
    public Float getPercentage() {
        return this.percentage;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(countrycode);
        sb.append("|");
        sb.append(language);
        sb.append("|");
        sb.append(isofficial);
        sb.append("|");
        sb.append(percentage);
        return sb.toString(); 
    } 


}
