/*
 * Created on 2020-05-29 ( Time 16:10:06 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package org.demo.bean;

import java.io.Serializable;

import javax.validation.constraints.*;


public class Country implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    @Size( min = 1, max = 3 )
    private String code;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    @Size( min = 1, max = 52 )
    private String name;

    @NotNull
    @Size( min = 1, max = 13 )
    private String continent;

    @NotNull
    @Size( min = 1, max = 26 )
    private String region;

    @NotNull
    private Float surfacearea;


    private Short indepyear;

    @NotNull
    private Integer population;


    private Float lifeexpectancy;


    private Float gnp;


    private Float gnpold;

    @NotNull
    @Size( min = 1, max = 45 )
    private String localname;

    @NotNull
    @Size( min = 1, max = 45 )
    private String governmentform;

    @Size( max = 60 )
    private String headofstate;


    private Integer capital;

    @NotNull
    @Size( min = 1, max = 2 )
    private String code2;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setCode( String code ) {
        this.code = code ;
    }

    public String getCode() {
        return this.code;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setName( String name ) {
        this.name = name;
    }
    public String getName() {
        return this.name;
    }

    public void setContinent( String continent ) {
        this.continent = continent;
    }
    public String getContinent() {
        return this.continent;
    }

    public void setRegion( String region ) {
        this.region = region;
    }
    public String getRegion() {
        return this.region;
    }

    public void setSurfacearea( Float surfacearea ) {
        this.surfacearea = surfacearea;
    }
    public Float getSurfacearea() {
        return this.surfacearea;
    }

    public void setIndepyear( Short indepyear ) {
        this.indepyear = indepyear;
    }
    public Short getIndepyear() {
        return this.indepyear;
    }

    public void setPopulation( Integer population ) {
        this.population = population;
    }
    public Integer getPopulation() {
        return this.population;
    }

    public void setLifeexpectancy( Float lifeexpectancy ) {
        this.lifeexpectancy = lifeexpectancy;
    }
    public Float getLifeexpectancy() {
        return this.lifeexpectancy;
    }

    public void setGnp( Float gnp ) {
        this.gnp = gnp;
    }
    public Float getGnp() {
        return this.gnp;
    }

    public void setGnpold( Float gnpold ) {
        this.gnpold = gnpold;
    }
    public Float getGnpold() {
        return this.gnpold;
    }

    public void setLocalname( String localname ) {
        this.localname = localname;
    }
    public String getLocalname() {
        return this.localname;
    }

    public void setGovernmentform( String governmentform ) {
        this.governmentform = governmentform;
    }
    public String getGovernmentform() {
        return this.governmentform;
    }

    public void setHeadofstate( String headofstate ) {
        this.headofstate = headofstate;
    }
    public String getHeadofstate() {
        return this.headofstate;
    }

    public void setCapital( Integer capital ) {
        this.capital = capital;
    }
    public Integer getCapital() {
        return this.capital;
    }

    public void setCode2( String code2 ) {
        this.code2 = code2;
    }
    public String getCode2() {
        return this.code2;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(code);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(continent);
        sb.append("|");
        sb.append(region);
        sb.append("|");
        sb.append(surfacearea);
        sb.append("|");
        sb.append(indepyear);
        sb.append("|");
        sb.append(population);
        sb.append("|");
        sb.append(lifeexpectancy);
        sb.append("|");
        sb.append(gnp);
        sb.append("|");
        sb.append(gnpold);
        sb.append("|");
        sb.append(localname);
        sb.append("|");
        sb.append(governmentform);
        sb.append("|");
        sb.append(headofstate);
        sb.append("|");
        sb.append(capital);
        sb.append("|");
        sb.append(code2);
        return sb.toString(); 
    } 


}
