/*
 * Created on 2020-05-29 ( Time 16:10:06 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package org.demo.business.service;

import java.util.List;

import org.demo.bean.City;

/**
 * Business Service Interface for entity City.
 */
public interface CityService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	City findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<City> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	City save(City entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	City update(City entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	City create(City entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


}
