/*
 * Created on 2020-05-29 ( Time 16:10:09 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package org.demo.business.service;

import java.util.List;

import org.demo.bean.Country;

/**
 * Business Service Interface for entity Country.
 */
public interface CountryService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param code
	 * @return entity
	 */
	Country findById( String code  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Country> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Country save(Country entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Country update(Country entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Country create(Country entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param code
	 */
	void delete( String code );


}
