/*
 * Created on 2020-05-29 ( Time 16:10:10 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package org.demo.business.service;

import java.util.List;

import org.demo.bean.Countrylanguage;

/**
 * Business Service Interface for entity Countrylanguage.
 */
public interface CountrylanguageService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param countrycode
	 * @param language
	 * @return entity
	 */
	Countrylanguage findById( String countrycode, String language  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Countrylanguage> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Countrylanguage save(Countrylanguage entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Countrylanguage update(Countrylanguage entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Countrylanguage create(Countrylanguage entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param countrycode
	 * @param language
	 */
	void delete( String countrycode, String language );


}
