/*
 * Created on 2020-05-29 ( Time 16:09:30 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package org.demo.web.listitem;

import org.demo.bean.City;
import org.demo.web.common.ListItem;

public class CityListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public CityListItem(City city) {
		super();

		this.value = ""
			 + city.getId()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = city.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
